language: node_js
node_js:
  - "10"
  - "8"


before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
  - PATH=$HOME/.cargo/bin:$PATH
  - sudo apt update -y
  - sudo apt install libusb-dev libusb-1.0 -y
  - npm i -g neon-cli
  - npm i

install:
  neon build

script: npx jest
